apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    opendatahub.io/notebook-image-desc: Jupyter notebook image with a set of data science libraries
    opendatahub.io/notebook-image-name: Custom Data Science
    opendatahub.io/notebook-image-url: https://github.com/tsailiming/custom-odh-jupyterhub-notebook
  labels:
    component.opendatahub.io/name: jupyterhub
    opendatahub.io/component: "true"
    opendatahub.io/notebook-image: "true"
  name: custom-data-science-notebook
  namespace: odh
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      opendatahub.io/notebook-python-dependencies: >-
        [{"name":"Boto3","version":"1.17.11"},{"name":"Kafka-Python","version":"2.0.2"},{"name":"Matplotlib","version":"3.4.2"},{"name":"Numpy","version":"1.21.0"},{"name":"Pandas","version":"1.2.5"},{"name":"Scipy","version":"1.7.0"},{"name":"Opencv-contrib-python","version":"4.4.0.46"}]
      opendatahub.io/notebook-software: '[{"name":"Python","version":"v3.8.6"}]'
    from:
      kind: DockerImage
      name: image-registry.openshift-image-registry.svc:5000/odh/custom-notebook-image:latest
    generation: 2
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
